application: idealive-devfest-2014
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
# Serve images as static resources.
- url: /static
  static_dir: web/static

- url: /
  script: web/index.html

- url: /idea.hml
  script: web/idea.html
